services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env